micronaut:
  application:
    name: student_micronaut
  netty:
    event-loops:
      threads: 16
  server:
    port: 8080

flyway:
  datasources:
    default:
      enabled: true
      url: ${FLYWAY_URL:`jdbc:postgresql://localhost:5432/student`}
      user: ${FLYWAY_USER:student}
      password: ${FLYWAY_PASS:student}

r2dbc:
  datasources:
    default:
      driver: pool
      protocol: postgresql
      url: ${R2DBC_URL:`r2dbc:postgresql://localhost:5432/student`}
      username: ${R2DBC_USER:student}
      password: ${R2DBC_PASS:student}
      pool:
        initial-size: 20
        max-size: 50







